### ISSUE TITLE
arctos: no accepted georeferences

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#107]
@dustymc
The location table should most likely fill `accepted_georeference_id`. Many of the locations have a georeference, but it isn't listed as accepted. So unless they are explicitly discarded/mistrusted georeferences, then `accepted_georeference_id` should be filled.

See [comment](https://github.com/gbif/model-material/issues/98#issuecomment-1453782842) that explains when accepted_georeference should be filled

I'm not sure about how this relates to the `georeference_verification_status` on occurrences. I notice that the wast majority of occurrences have status: `unverified`. But even those that are listed as `accepted` have no`accepted_georeference_id`.

@tucotuco you might be able to untangle this. I'm not sure what the correct use is.

**Comment by dustymc** [comment]
>accepted_georeference_id

possibly understood and tentatively corrected: I've just mapped georeference. georeference_id and location. location_id to share the same value (because they're part of the same object before being ripped apart for the GUM).

**Comment by tucotuco** [comment]
Though this won't break anything in the current model or exercise, it isn't rigorously correct in the Unified Model because a Location is modeled as a place and a Georeference as an interpretation of the place as a spatial description. In other words, they are different concepts (classes) and if this ever moved into a semantic realm there would be a logical inconsistency between the two.

@dustymc  That having been said, the reason the Georeferences are separate from the Locations in the Unified Model was specifically to handle Arctos. So what did I get wrong?

Can a cataloged item have several Locations in Arctos?

**Comment by tucotuco** [comment]
Ah, with the accompanying conclusion that it is fine to use the location_id for the georeference_id.

**Comment by tucotuco** [comment]
The accepted_georeference_id is now populated whenever appropriate. Closing issue.
