### ISSUE TITLE
Koldingensis: identifications do not use agents

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#18]
I see the fields `identifiedBy` and `identifiedById` on identifications. I would have expected them to be agents

```gql
query {
  # start with the preserved specimen fetched by ID (is there an occurrence ID or such that I could use?)
  specimen: allMaterialEntities(condition: {materialEntityId: "5c488c08-8cab-444a-9598-806dd0abec85"}) {
    nodes {
      materialEntityType
      preparations
      catalogNumber
      recordedBy
      entityByMaterialEntityId {
        entityType
        identificationEvidencesByEntityId {
          nodes {
            identificationByIdentificationId {
              dateIdentified
              identificationType
              verbatimIdentification
              # I would have thought the people identifying would be considered agents?
              identifiedBy
              identifiedById
            }
          }
        }
      }
    }
  }
  # I had expected a reference to these agents instead
  allAgents {
    nodes {
      agentType
      preferredAgentName
    }
  }
}
```

**Comment by MortenHofft** [comment]
I'm not entirely sure what the goal is here - but it seems related to this section
https://github.com/gbif/model-material/blob/master/data-mapping.md#general-considerations

> Some AgentRoles are currently made explicit in the UM. Most of these are simply fields for the name of the Agent fulfilling the role (e.g., georeferencedBy), while others are fields for an Agent identifier (e.g., recordedByID. Following are lists of explicit AgentRole fields in the UM, separated by the concept they can be found in. Separate AgentRole records for these are not necessary.

I understand this as meaning that  `identifiedById` should be a FK to the agent table?

**Comment by timrobertson100** [comment]
`identifiedById` will not necessarily be a foreign key to the Agent. It will be in this example because of how I chose the IDs for Agent. It could be repeated as an Identifier attached to the Agent.

There is basically some duality of fields in this model. 
1. An Entity having an Identification performed by an Agent with an Identifier
2. The Entity having the `identifiedByID` that captures the same above

It's something I question as the unified model develops. Ambiguity and multiple ways to represent the same thing will lead to fragility. It's there for now because we put in all DwC fields from the current DwC that would be possible.

I think it would be reasonable to remove the `identifiedByID` values in Koldingenis as we have modeled this with the normalized Agent with AgentRole approach. Seem sensible?

**Comment by MortenHofft** [comment]
Yes I would be in favour of removing the plain `identifiedBy` and `identifiedByID` values. As a consumer it is frustrating when you do not know what to trust and as a producer it leaves doubt (though I'm sure some also appreciate the option to choose the simple option).

So the graphQL schema would ideally expand that (in future versions). For now it would be done like this if I understand correctly. To get the agents behind the 2 identifications

```gql
visualIdentificationBy: allAgentRoles(condition: {agentRoleTargetId: "27b13f41-87f2-46f0-8c8a-93d98412ef82", agentRoleTargetType: IDENTIFICATION}) {
    nodes {
      agentRoleAgentName
      agentRoleAgentId
    }
  }
  dnaIdentificationBy: allAgentRoles(condition: {agentRoleTargetId: "aadb06f5-f746-48fa-8cc2-1c70f4765f15", agentRoleTargetType: IDENTIFICATION}) {
    nodes {
      agentRoleAgentName
      agentRoleAgentId
    }
  }
```

Even in our simple example the values aren't aligned (the agent table says something different than the identifiedBy field)
