### ISSUE TITLE
specify: duplicate citation entries

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#37]
I cannot import as there are duplicate entries in the citation table. E.g.
https://github.com/gbif/model-material/blob/master/specify/Citation/CITATION.csv#L2586

**Comment by tucotuco** [comment]
@MortenHofft @timrobertson100 I suspect this comes about because a specimen is mentioned several times in a single journal article, and the page numbers of the citation are not included to differentiate them. It is also feasible that a specimen could be cited multiple times on the same page, so I am inclined to think that the constraint we are trying to enforce is not a reasonable one.

**Comment by timrobertson100** [comment]
I suspect you're correct that is the reason, but can we think of any use where a repeated "this material is cited in an article" would be useful?

**Comment by tucotuco** [comment]
I am not sure it is a matter of useful. I think it is a matter of every citation being captured in the raw data, and therefore that is what will come through naturally without manipulation on the part of the data provider. @Jegelewicz  I am curious to know if this happens commonly in Arctos as well.

**Comment by Jegelewicz** [comment]
I wouldn't think so because citations are tied to identifications so unless a cataloged item was cited as two different taxa in a single paper, it shouldn't. That doesn't mean it 100% couldn't happen though! Let me check around.

**Comment by dustymc** [comment]
```
arctosprod@arctos>> \d citation
...
    "ix_u_citation_idx" UNIQUE, btree (publication_id, collection_object_id)
```

**Comment by tucotuco** [comment]
@dustymc That's a clear answer. It can't happen by design in Arctos.

@acbentley We're curious how this duplication comes about to know what the effect would be of deduplicating them on export in order to meet the constraints that are in place.

**Comment by acbentley** [comment]
I am doing this as a collection object query in Specify using collection object GUIDs as the ID.  There are cases where the same collection object has been referenced in multiple reference works (thus duplicated citation_target_ids) and where multiple collection objects are cited in the same reference work (thus duplicated citation_reference_ids), but there shouldn't be any cases where the same collection object is cited multiple times in the SAME citation (combination of citation_target_id and citation_reference_id).  If it is the latter that is the problem then it may be due to 1:M issues again, OR,  if I run the original query with the distinct option checked I get 9225 records instead of 9233 so maybe there is a reference here and there that has been entered twice for the same collection object.  Below is a new file with that duplication removed (hopefully).

[CITATION.csv](https://github.com/gbif/model-material/files/10709338/CITATION.csv)

**Comment by tucotuco** [comment]
@acbentley That did indeed produce unique rows. Thanks.
