### ISSUE TITLE
Specify: empty tables, expected or not?

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#63]
Below is a list of tables in the model. I've striked the ones that are not included in the specify export. Could we start by confirming that this is expected. For example there are no `occurrence` and no `identification_evidence`. This hasn't changed at any point, but I would like to be sure it is correct 😃 

* agent
* agent_relationship
* agent_role
* citation
* digital_entity
* entity
* entity_relationship
* event
* georeference
* identification
* location
* material_entity
* organism
* reference
* taxon
* taxon_identification
* ~agent_group~
* ~assertion~
* ~chronometric_age~
* ~collection~
* ~genetic_sequence~
* ~geological_context~
* ~identification_evidence~ See also #61
* ~identifier~ See also #59
* ~material_group~
* ~occurrence~
* ~occurrence_evidence~ See also #60
* ~protocol~

**Comment by acbentley** [comment]
I will let @tucotuco weigh in here but I don't think any of those tables need to be populated for a specimen-based collection.

**Comment by tucotuco** [comment]
It is feasible that a collection would have data for every one of those tables. As I understand it, for Andy's data set there are no data for the following tables:

* ~agent_group~
* ~chronometric_age~
* ~genetic_sequence~
* ~geological_context~
* ~identification_evidence~ See also #61
* ~occurrence_evidence~ See also #60
* ~protocol~

I believe there are data in Andy's database for the following tables, but they have not been extracted.
* assertion
* collection
* identifier
* occurrence

**Comment by acbentley** [comment]
We now have assertion and occurrence.  What is expected for the collection and identifier tables?

Collection like this?

[COLLECTION.csv](https://github.com/gbif/model-material/files/10735840/COLLECTION.csv)

**Comment by tucotuco** [comment]
That looks like a fine Collection. Note that Collections are also a subtype of Agent (they can act, doing things such as accession, loan, etc.) and therefore need a corresponding Agent record.

Anything in your dataset that has alternative identifiers could go in the identifier table. This might include things like ORCIDs for Agents, CatalogNumbers and otherCatalogNumbers for collection objects, FieldNumbers for Events, etc.

**Comment by acbentley** [comment]
In Specify they cannot act as agents for any other records or actions.  Do I still need to add it?

**Comment by acbentley** [comment]
For identifiers, both catalog number and field number are already in the material_entity and Event tables.  Do I need to repeat?  I do have some other catalog numbers and agent ORCID ids that I could put here.  What would the identifier_target_type and identifier_type be for these?

**Comment by acbentley** [comment]
Could Specify URL's to CO's also go here as @MortenHofft suggests?  I currently cannot pull those out through a query but could post process them by using the catalog number and a base URL.

**Comment by tucotuco** [comment]
> In Specify they cannot act as agents for any other records or actions. Do I still need to add it?

Yes, a Collection is an Agent in the Unified Model and needs that parent.

**Comment by acbentley** [comment]
So, how would I add it into the current three fields in that table?  GUID, agent_type = collection, preferred_agent_name = ?

**Comment by tucotuco** [comment]
Right. Specifically,

"3f55b3fa-292d-4170-bd46-66dca41d7f05","COLLECTION", "KUBI Ichthyology Collection"

**Comment by tucotuco** [comment]
> For identifiers, both catalog number and field number are already in the material_entity and Event tables. Do I need to repeat? I do have some other catalog numbers and agent ORCID ids that I could put here. What would the identifier_target_type and identifier_type be for these?

No, you don't need to repeat those catalog numbers and field numbers since they are already explicitly declared in the appropriate tables.

**Comment by tucotuco** [comment]
> Could Specify URL's to CO's also go here as @MortenHofft suggests? I currently cannot pull those out through a query but could post process them by using the catalog number and a base URL.

Yes, they definitely could.

**Comment by acbentley** [comment]
Here is agent file with collection added

[AGENT.csv](https://github.com/gbif/model-material/files/10748177/AGENT.csv)

**Comment by acbentley** [comment]
and here is the identifier table.  Wasn't sure what should go in identifier_target_type and identifier_type so just guessed.  Let me know if they need to be altered.

[IDENTIFIER.csv](https://github.com/gbif/model-material/files/10748207/IDENTIFIER.csv)

**Comment by acbentley** [comment]
There are lots of files that have been changed in the original file set I sent you.  At some point it would probably be good to replace everything in the specify folder with a new set once we have all issues resolved.

**Comment by timrobertson100** [comment]
> At some point it would probably be good to replace everything in the specify folder with a new set once we have all issues resolved

You have commit access @acbentley. Please can you put your files in the [Specify folder](https://github.com/gbif/model-material/tree/master/specify) rather than attach them to issues? You just go to the folder, and upload, and it will overwrite the previous one.

**Comment by acbentley** [comment]
Tim

Morten had asked me to put them in issues so that he would see them and be able to keep up with changes.  I am happy to change them myself if that is more expedient.

Andy

    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Forcid.org%2F0000-0002-3093-1258&data=04%7C01%7Cabentley%40ku.edu%7C5720c0e4d0f94b9e0df008da0127752c%7C3c176536afe643f5b96636feabbe3c1a%7C0%7C0%7C637823566221065460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LFnPbiFA9HMZ8k85%2F0%2FOx5vJxTNhZTjAo7S%2BqrDAh6c%3D&reserved=0>
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V


From: Tim Robertson ***@***.***>
Reply-To: gbif/model-material ***@***.***>
Date: Thursday, February 16, 2023 at 3:27 AM
To: gbif/model-material ***@***.***>
Cc: Andrew Bentley ***@***.***>, Mention ***@***.***>
Subject: Re: [gbif/model-material] Specify: empty tables, expected or not? (Issue #63)


At some point it would probably be good to replace everything in the specify folder with a new set once we have all issues resolved

You have commit access @acbentley<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Facbentley&data=05%7C01%7Cabentley%40ku.edu%7C51aacde533964ba7609308db0ffff34a%7C3c176536afe643f5b96636feabbe3c1a%7C0%7C0%7C638121364201351969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ovOSVj9sldjRWSWBbcQj9vSbcqtWxFoGU7KSwBnK2i0%3D&reserved=0>. Please can you put your files in the Specify folder<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgbif%2Fmodel-material%2Ftree%2Fmaster%2Fspecify&data=05%7C01%7Cabentley%40ku.edu%7C51aacde533964ba7609308db0ffff34a%7C3c176536afe643f5b96636feabbe3c1a%7C0%7C0%7C638121364201351969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=e8LQgIw5ZtvcWxWLIOFGoSI%2FsiqboKC8lQr0FsdiTuw%3D&reserved=0> rather than attach them to issues? You just go to the folder, and upload, and it will overwrite the previous one.

**Comment by MortenHofft** [comment]
I would prefer if you simply uploaded them and referenced/commented in the issue so we could see that it was updated. That is what I've been doing when you attach them to issues, updating the repo on your behalf: e.g. https://github.com/gbif/model-material/commit/9030e8cf5516398a4c5b8b2b4f6e63ff76efeca5

But it would be far more convenient for me if you did it 😄

**Comment by acbentley** [comment]
Sounds good.  I will do that from now onwards and at some point will upload new versions of all directories to make sure that all files are up to date.
