### ISSUE TITLE
Specify: citations meaning of target and type

### ISSUE THREAD

**Issue by MortenHofft** [gbif/model-material#71]
From the citation file i took below line
`dcc04c84-1ed3-11e3-bfac-90b11c41863e,ORGANISM,dc3f659f-8c8c-4740-b2c2-c57c47f6125d,JOURNAL_ARTICLE,,`
using the ID from https://ichthyology.specify.ku.edu/specify/view/collectionobject/38640/

I'm wondering if the citation is best attached to the organism or the material_entity (`citationTargetType=MATERIAL_ENTITY|ORGANISM`)
What is the difference in meaning between the two? 

and secondly if `JOURNAL_ARTICLE` is the intended type for the `citationType`. I had expected something like `CITED_IN`.

**Comment by MortenHofft** [comment]
from the [common models document](https://docs.google.com/document/d/1ZTMt-V3U0D0761bqqogeN58MjuHhIs_Kisu6CRtl-uA/edit)

> Example
A Citation for a GeneticSequence would have an citationTargetID populated with a value from the geneticSequenceID field of the matching row in the GeneticSequence table. The citationTargetType would be 'GENETIC_SEQUENCE'. The citationType would be a controlled vocabulary term for what kind of citation it was (e.g., 'taxonomic revision').

**Comment by tucotuco** [comment]
The citationTargetType should be the type of the thing cited. In your example, the Organism. The difference in meaning is based on the definitions of the classes. In practical terms, since we do not have formal definitions, the properties of the classes distinguish them. A MaterialEntity is a broader term that includes Organisms (as a formal subtype) and other material things, such as parts of organisms, soil samples, DNA extracts, etc. 

Hmm, interesting observation. JOURNAL_ARTICLE would be a better value for the reference_type, wouldn't it?  But `CITED_IN` would be a pretty boring citationType as everything would have that same citationType. The point behind citationType is to say what the reference has to say about the target. That's why the example 'taxonomic revision'.

**Comment by MortenHofft** [comment]
Before reading the example I assumed it was used to indicate the direction. As in this information is based on that paper. Versus this material is cited in that paper. So a way to allow outgoing as well as incoming citations. But the 'taxonomic revision' example also makes sense.
