### ISSUE TITLE
Arctos: Unexpected additional columns in files

### ISSUE THREAD

**Issue by timrobertson100** [gbif/model-material#93]
I'm trying to load in the Arctos export with [this simple script](https://github.com/gbif/model-material/blob/master/gbif/load-arctos.sql).

It fails with: 
```
psql:load-arctos.sql:14: ERROR:  extra data after last expected column
CONTEXT:  COPY entity, line 2: "https://arctos.database.museum/guid/MSB:Host:24659,MATERIAL_ENTITY,https://arctos.database.museum/co..."
```

The first lines of the entity file have:
```
$ head -3 ../arctos/entity.csv 
entity_id,entity_type,dataset_id,entity_name,entity_remarks,arctos_cid,arctos_pid,arctos_mid
https://arctos.database.museum/guid/MSB:Host:24659,MATERIAL_ENTITY,https://arctos.database.museum/collection/MSB:Host,,Host of SP1,30109430,,
https://arctos.database.museum/guid/MSB:Host:24660,MATERIAL_ENTITY,https://arctos.database.museum/collection/MSB:Host,,,30109436,,
```

Is it possible to have the arctos files without the additional columns, please (i.e. exactly our schema)? If that is not a simple ask, I'll tweak the load scripts to reference the columns directly.

**Comment by timrobertson100** [comment]
Ping @dustymc

**Comment by dustymc** [comment]
Bah, sorry, I forgot to strip those - I'll get new data in a bit.

**Comment by timrobertson100** [comment]
Thank you - no problem at all.

If you get a chance, please can you try and run the load from CSV into an empty database to test it? It'll be what we do, so you might spot obvious things quickly.

To save effort, it'd be something like this:

```
psql
create database material_model;
create user material with encrypted password '<PASSWORD>';
grant all privileges on database material_model to material;
\q
psql postgresql://material:<PASSWORD>@pg1.gbif-uat.org/material_model -f schema.sql
```

The schema is [here](https://github.com/gbif/model-material/blob/master/schema.sql) and then I think [these commands](https://github.com/gbif/model-material/blob/master/gbif/load-arctos.sql) woudl cover your CSVs.

**Comment by dustymc** [comment]
Tim, I unfortunately do not have that capability.

I believe the only other blatant violation of the schema I made is in regards to taxon_order - I changed it to an int so I could fit within the pkey.

Either way, I have to fake data here. We currently have only two "ranks" (0,1) but are moving towards a model that's more of a spectrum (0..1 or ``smallint`` or ?? )- the model isn't written yet so who knows, but all same idea: we may have many equally-valid, unordered, nonunique identifications for any item (and optionally more ordered data, but those should not be a concern). We believe that to be the best approach when eg molecular and morphometric data agree (the taxa/concept may be identical and we don't want to be forced to choose a 'best'), but it is particularly necessary in cultural collections where one [item](https://arctos.database.museum/guid/UAM:EH:0610-5898) may be identified (often by multiple teams) *simultaneously* as https://arctos.database.museum/name/Parka, https://arctos.database.museum/name/Rangifer, https://arctos.database.museum/name/Alnus, https://arctos.database.museum/name/Oncorhynchus, and potentially many more. (The change will essentially allow each of those taxa to be a full-fledged co-equal identification capable of carrying its own attribution and metadata, rather than being stuffed into our 'its weird' handler.)

If the GUM might accommodate that in some way, I would be very happy to rebuild.

**Comment by timrobertson100** [comment]
@dustymc @tucotuco 

I'm really sorry! I totally missed there was an arctos data drop 2 days ago.
I have loaded the data and the (work in progress) UI can be used to show any entity using your IDs, such as [this example](http://labs.gbif.org:7003/?entityId=https://arctos.database.museum/guid/MSB:Host:15217).

@MortenHofft - it might be worth advising a vocabulary mapping for the relationship types that would allow the media to show.

**Comment by dustymc** [comment]
Neat, and thanks!

FYI here are our media relationships: https://arctos.database.museum/info/ctDocumentation.cfm?table=ctmedia_relationship

**Comment by tucotuco** [comment]
Solved. Closing.
